cnn_channels: 64
dense_channels: 64
out_channels: 1
nfeatures: ${transform.nfeatures}
series_length: ${transform.series_length}
num_cnn_layers: 3
num_blocks: 7
pool_size: 2
stride: 1
kernel_size: 3
cnn_expansion_factor: 4

