mtype: "cnn.regression"
cnn_channels: 64                                # Number of channels in first CNN layer
dense_channels: 64                              # Number of channels in dense layer
out_channels: 1                                 # Number of network output channels
num_cnn_layers: 3                               # Number of CNN layers in a CNN block
num_blocks: 8                                   # Number of CNN blocks in the network
pool_size: 2                                    # Max pool size for every block
stride: 1                                       # Stride value for every CNN layer
kernel_size: 3                                  # Kernel size for every CNN layer
cnn_expansion_factor: 4                         # Increase in the number of channels from one CNN layer to the next
base_freq:  ${data.base_freq}                   # Start frequency of base octave
feature: 1
fold_octaves: False


