  context_len:  512
  horizon_len:  128
  input_patch_len:  32
  output_patch_len:  128
  num_layers:  20
  num_heads:  16
  model_dims:  1280
  per_core_batch_size:  32
  backend: "gpu"
  use_positional_embedding: False
  point_forecast_mode:  "median"