mtype: "transformer"
task:           "regression"
nheads: 32                # (int): Number of heads
dropout: 0.0              # (float): Dropout probability
bias: True                # (bool): Whether to add bias to input projection.
E_head: 512             # (int): Head dim
E_internal: 512
nlayers: 1
fold_octaves: False
