nheads: 16                # (int): Number of heads
dropout: 0.0              # (float): Dropout probability
bias: True                # (bool): Whether to add bias to input projection.
E_head: 512             # (int): Head dim
E_internal: 512
E_out: 1               # (int): Size of layer output
nlayers: 4