defaults:
  - platform: "explore"
  - train: "baseline_cnn"
  - transform: "wp-scaled"
  - data: "sinusoids_small.nc"
  - model: "wp_cnn"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

