optim: rms                                              # Optimizer
lr: 0.001                                                 # Learning rate
nepochs: 5000                                           #  Training Epochs
refresh_state: False                                    # Start from random weights (Ignore existing checkpoints)
overwrite_log: True                                     # Start new log file
results_path: "${platform.project_root}/results"        # Save results here
weight_decay: 0.0                                       # Weight decay parameter for optimizer
mode:  train                                            # execution mode: 'train' or 'valid'
base_freq:  ${data.base_freq}                           # lowest value of freq range

