project_root:      "/Users/tpmaxwel/Data/astrotime"
model_root: "${.project_root}/models/"
results:    "${.project_root}/results"
cache:      "${.project_root}/cache"
processed:  '${.project_root}/processed'
gpu: -1

