project_root:  "/explore/nobackup/projects/ilab/data/astrotime"   # Checkpoint and log files are saved under this directory
gpu: 0                                                            # Index of gpu to execcute on
log_level: "info"                                                 # Log level: typically debug or info