defaults:
  - platform: "explore"
  - train: "MIT_cnn.classification.octaves"
  - transform: "MIT"
  - data: "MIT"
  - model: "cnn.classification.octaves"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

