defaults:
  - platform: "explore"
  - train: "sinusoid_cnn"
  - transform: "sinusoid"
  - data: "sinusoids"
  - model: "wp_cnn"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

