defaults:
  - platform: "explore"
  - train: "poly_cnn"
  - transform: "poly"
  - data: "sinusoids.nc"
  - model: "poly_cnn"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

