defaults:
  - platform: "explore"
  - train: "baseline_cnn"
  - transform: "wwz"
  - data: "sinusoids_small.nc"
  - model: "baseline_cnn"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

