defaults:
  - platform: "explore"
  - train: "synthetic_cnn"
  - transform: "synthetic"
  - data: "astro_synthetic_autocorr"
  - model: "wp_cnn"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

