defaults:
  - platform: "explore"
  - train: "synthetic_cnn"
  - transform: "synthetic.octave"
  - data: "synthetic.octave"
  - model: "cnn.octave_regression"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

