defaults:
  - platform: "explore"
  - train: "synthetic_transformer"
  - transform: "transformer"
  - data: "synthetic"
  - model: "transformer"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

