defaults:
  - platform: "explore"
  - train: "synthetic_cnn.classification.octave_partition"
  - transform: "synthetic.oparts"
  - data: "synthetic"
  - model: "cnn.classification.octave_partition"
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

