sparsity:   0.0                       # Fraction of observations to drop (randomly)
batch_size: ${data.batch_size}      # Batch size for training
nfreq_oct:  ${data.nfreq_oct}       # Number of frequency values (log2 spaced) in each octave
base_freq:  ${data.base_freq}       # Start frequency of base octave
noctaves:   ${data.noctaves}        # Number of octaves in base frequency space
test_mode:  ${data.test_mode}
time_scale:   1.0                   # Time rescale factor for shifted frequency range
decay_factor: 0.0                   # Time envelope decay factor
fold_harmonic: true                  # Add folded harmonic as additional features of output
sum_features: false                  # Output the sum over harmonics at each freq
subbatch_size: 2                     # If>0: Split batches into (serially computed) subbatches in order to fit into gpu memory
feature: 1



