nfeatures: 1                        # Number of feaatures to be passed to network
sparsity: 0.0                       # Fraction of observations to drop (randomly)
batch_size: ${data.batch_size}      # Batch size for training