series_length: 1536                 # Length of subset of input timeseries to process
sparsity: 0.0                       # Fraction of observations to drop (randomly)
batch_size: ${data.batch_size}      # Batch size for training
nfreq: 256                          # Number of frequency values to compute (spectral resolution)
base_freq_range:                    # Base frequency range in computed spectra (before time rescaling)
  - 0.1
  - 10.0
fscale: "log"                       # Scale of frequency axis
kernel_size: 82                     # Size of wpk conv kernel
nkernels: 32
kernel_time_spacing: 0.6
envelope_reduction_factor: 1.0
nfeatures: 64


