series_length: 1536                 # Length of subset of input timeseries to process
sparsity: 0.0                       # Fraction of observations to drop (randomly)
batch_size: ${data.batch_size}      # Batch size for training
nfreq: 256                          # Number of frequency values to compute (spectral resolution)
freq_start: 0.1                     # Lowest frequency value in computed spectra
freq_end: 10.0                      # Highest frequency value in computed spectra
fscale: "log"                       # Scale of frequency axis
kernel_size: 128                    # Size of wpk conv kernel
nkernels: 64
kernel_time_spacing: 1.0


