version: 1
formatters:
  simple:
    format: '[%(levelname)s] - %(message)s'
handlers:
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${platform.project_root}/logs/astrotime.${train.version}.csv
root:
  handlers: [file]

disable_existing_loggers: false